spring.application.name=cementerio_api
# Conexión a tu base de datos MySQL (ajusta el nombre de la BD, usuario y contraseña)
spring.datasource.url=jdbc:mysql://10.10.20.31:3317/conecta?serverTimezone=UTC&maxAllowedPacket=67108864
spring.datasource.username=conecta_user
spring.datasource.password=conecta_pass

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/swagger-ui.html
